// <auto-generated />
using System;
using ClinicPacServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClinicPacServer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200122001758_prevision")]
    partial class prevision
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClinicPacServer.Models.Consultation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Document");

                    b.Property<string>("Name");

                    b.Property<DateTime>("NoTicketDate");

                    b.Property<DateTime>("PaidDate");

                    b.Property<int>("State");

                    b.Property<string>("Surgery");

                    b.Property<DateTime>("TicketDate");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("ClinicPacServer.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("ActiveCode");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Prevision");

                    b.Property<int>("Rol");

                    b.Property<string>("Token");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClinicPacServer.Models.Consultation", b =>
                {
                    b.HasOne("ClinicPacServer.Models.User", "User")
                        .WithMany("Consultations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
